### ISSUE TITLE
github.com/go-redis/redis/v8".Client does not implement "github.com/redis/go-redis/v9".Cmdable (wrong type for method Append)

### ISSUE THREAD

**Issue by cmagorian** [dranikpg/gtrs#10]
Not entirely sure if this is a configuration issue, but found this from copy/pasted code from the gtrs-test example.

**Comment by cmagorian** [comment]
Upgrading the v9 solved the issue, maybe should update the example in gtrs-test.

**Comment by dranikpg** [comment]
Oh yes, the library evolved since then, will fix it, thanks!
