### ISSUE TITLE
GroupConsumer without StreamIDs

### ISSUE THREAD

**Issue by NuVivo314** [dranikpg/gtrs#14]
Hello,

I am curious to know if there is a specific reason for not utilizing the StreamIDs map for GroupStreams.

If there isn't one, I would like to suggest a merge request.

Bye

**Comment by dranikpg** [comment]
> Would you like me to create a new struct (like: MultiGroupConsumer? GroupConsumerStreams ? ) to avoid breaking the existing contract ?

No, no new struct is needed. We have the construction function `NewGroupConsumer`, you can add a new constructing function like `NewMultiGroupConsumer` which'll accept a StreamIDs, this way nothing breaks

> opportunity to discuss what you want for "good tests"

Just a test with multiple groups and streams, to make sure that you properly update the lastID for each stream independently 🙂
