### ISSUE TITLE
Observability Issues 

### ISSUE THREAD

**Issue by mtyazici** [dranikpg/gtrs#20]
Hi, we are using ConsumerGroups and had an unexpected issue with the length of pending entries list (PEL) increasing. We are not sure what the root cause is but felt having observability on the ConsumerGroup side would help narrow down the search space. 

Do you have a plan to add observability or expose some fields like the length of the ACK buffer so we can add observability on the application level?

**Comment by dranikpg** [comment]
Hi. Added simple stats, feel free to ping if you need more help 🙂

**Comment by dranikpg** [comment]
Published https://github.com/dranikpg/gtrs/releases/tag/v0.6.1

**Comment by mtyazici** [comment]
Thanks a lot for the quick update :)
