### ISSUE TITLE
go-redis v9

### ISSUE THREAD

**Issue by hiendaovinh** [dranikpg/gtrs#5]
Thanks for the library! I'm experimenting it as an event bus for micro-services.
Are you considering creating a branch for client v9?
Have a great day!

**Comment by hiendaovinh** [comment]
Also, how about using *interface segregation* where you specify only necessary signatures instead of type-hint `redisv8.Cmdable`, `redisv8.XStream`, etc?

It should result in a more flexible library (works with both v8 and v9) afaik. Although it could take more effort from our end (consumer side).

**Comment by dranikpg** [comment]
Hi! Thanks for using gtrs 😄 

v9 is still beta, but it might make sense to support it. I'll do it over the weekend if I find no better idea.

The interface segregation idea looks interesting. However, gtrs needs at least some types internally to interact with the client. It could add its own interfaces, but this would make the code really complex. For example, the redis client often returns slices of responses (`redis.XMessage`), they are not easily castable. So this would require type erasing large parts of code and mapping types (I have `dto-mapper` for this 😆, but this would make many parts slower). Or is there a simpler solution?

**Comment by hiendv** [comment]
Yeah, totally agree. It would be tough. Maintaining two different versions of gtrs with v8 and v9 seems easier :laughing: .

**Comment by dranikpg** [comment]
Check out 
```
go get github.com/dranikpg/gtrs@client-v9
```
for v9 client. If I forget to update this branch, feel aways free to ping me.

**Comment by hiendaovinh** [comment]
Thanks for your work!
